Controllers/AnketController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;
using WebApplication1.Service;

namespace WebApplication1.Controllers
{
    [Authorize(Roles = "admin")]
    public class AnketController : Controller
    {
        private readonly AnketService anketService;
        public AnketController(AnketService anketService)
        {
            this.anketService = anketService;
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Edit(long id)
        {
            return View(anketService.FindById(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Anket anket)
        {
            if (ModelState.IsValid)
            {
                anketService.Save(anket);
                return RedirectToAction("Index", "Home");
            }
            return View(anket);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add(Anket anket)
        {
            if (ModelState.IsValid)
            {
                anketService.Save(anket);
                return RedirectToAction("Index", "Home");                
            }
            return View(anket);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Remove(long id)
        {
            anketService.Remove(id);
            return RedirectToAction("Index", "Home");
        }


        [AcceptVerbs("Get", "Post")]
        public IActionResult CheckName(string name)
        {
            if (anketService.CheckName(name))
                return Json(true);
            return Json(false);
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;
using WebApplication1.Service;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        private readonly AnketService anketService;

        public HomeController(AnketService anketService)
        {
            this.anketService = anketService;
        }

        [Authorize]
        public IActionResult Index()
        {
            /*if (User.Identity.IsAuthenticated)
            {
                ViewBag.Message = User.Identity.Name;
                ViewBag.Role = User.FindFirst(x => x.Type == ClaimsIdentity.DefaultRoleClaimType).Value;
            }*/
            return View(anketService.FindAll());
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;
using WebApplication1.Service;

namespace WebApplication1.Controllers
{
    [Authorize]
    public class TestController : Controller
    {
        private readonly AnketService anketService;
        private readonly ResultService resultService;

        public TestController(AnketService anketService, ResultService resultService)
        {
            this.anketService = anketService;
            this.resultService = resultService;
        }

        public IActionResult Run(long id)
        {
            ViewBag.DateNow = DateTime.Now;
            Anket anket = anketService.FindById(id);
            anket.Questions = anket.Questions
                .OrderBy(a => Guid.NewGuid()).ToList()
                .GetRange(0, anket.Questions.Count / 2);
            return View(anket);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Run(Dictionary<String, String> values)
        {
            DateTime date_begin = DateTime.Parse(values["DateNow"]);
            int anket_id = Convert.ToInt32(values["anket_id"]);
            Result result = resultService.Save(values, User.Identity.Name, anket_id, date_begin, DateTime.Now);
            return View("Answer", result);
        }
    }
}

Views/Home/Index.cshtml
@model List<WebApplication1.Models.Anket>
@{
    ViewData["Title"] = "Анкеты";
}

<h2>Анкеты</h2>

@if (this.User.IsInRole("admin"))
{
    <a asp-action="Add" asp-controller="Anket">
        <div class="card bg-light mb-3 text-center">
            <div class="card-header">Создать новую анкету</div>
        </div>
    </a>
}
<div class="card-columns">

    @foreach (var item in Model)
    {
        <div class="card bg-light mb-3 text-center">
            <div class="card-header">@Html.DisplayFor(modelItem => item.Name)</div>
            <div class="card-body">
                @if (this.User.IsInRole("admin"))
                {
                    <a asp-route-id="@item.Id" asp-action="Index" asp-controller="Question" class="btn btn-success card-link">
                        Вопросов: @Html.DisplayFor(modelItem => item.Questions.Count)
                    </a>
                }
                else
                {
                    <p class="card-text">Вопросов: @Html.DisplayFor(modelItem => item.Questions.Count)</p>
                }
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <a asp-route-id="@item.Id" asp-action="Run" asp-controller="Test" class="btn btn-primary">Начать тест</a>
                </li>
            </ul>
            @if (this.User.IsInRole("admin"))
            {
                <div class="card-footer d-flex justify-content-around">
                    <a asp-route-id="@item.Id" asp-action="Edit" asp-controller="Anket" class="btn btn-info card-link">Изменить</a>
                    @using (Html.BeginForm("Remove", "Anket", new { id = item.Id }, FormMethod.Post, true, new { onsubmit = "return confirm('Вы действительно хотите удалить " + item.Name + " ');return false;" }))
                    {
                        <input type="submit" value="Удалить" class="btn btn-danger card-link" />
                    }
                </div>
            }
        </div>
    }
</div>